"""initial tables

Revision ID: 30725b07b3d3
Revises: 
Create Date: 2026-03-17 22:44:19.778073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from app.models.types import JSONType


# revision identifiers, used by Alembic.
revision: str = '30725b07b3d3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_storage',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('storage_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('content', sa.LargeBinary(), nullable=False),
    sa.Column('content_type', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('sha256', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_storage_sha256'), 'file_storage', ['sha256'], unique=False)
    op.create_index(op.f('ix_file_storage_storage_id'), 'file_storage', ['storage_id'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('handle', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('image', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.Column('api_token_hash', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_handle'), 'users', ['handle'], unique=True)
    op.create_table('skills',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('tags', JSONType(), server_default='{}', nullable=False),
    sa.Column('stats', JSONType(), server_default='{}', nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skills_owner_id'), 'skills', ['owner_id'], unique=False)
    op.create_index(op.f('ix_skills_slug'), 'skills', ['slug'], unique=True)
    op.create_table('skill_moderation',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('skill_id', sa.Uuid(), nullable=False),
    sa.Column('is_suspicious', sa.Boolean(), nullable=False),
    sa.Column('is_malware_blocked', sa.Boolean(), nullable=False),
    sa.Column('verdict', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('reason_codes', JSONType(), server_default='[]', nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('engine_version', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('legacy_reason', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('evidence', JSONType(), server_default='[]', nullable=False),
    sa.Column('updated_at', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_moderation_skill_id'), 'skill_moderation', ['skill_id'], unique=True)
    op.create_table('skill_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('skill_id', sa.Uuid(), nullable=False),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('changelog', sa.Text(), nullable=False),
    sa.Column('changelog_source', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=True),
    sa.Column('files', JSONType(), server_default='[]', nullable=False),
    sa.Column('security', JSONType(), server_default='{}', nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_versions_skill_id'), 'skill_versions', ['skill_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_skill_versions_skill_id'), table_name='skill_versions')
    op.drop_table('skill_versions')
    op.drop_index(op.f('ix_skill_moderation_skill_id'), table_name='skill_moderation')
    op.drop_table('skill_moderation')
    op.drop_index(op.f('ix_skills_slug'), table_name='skills')
    op.drop_index(op.f('ix_skills_owner_id'), table_name='skills')
    op.drop_table('skills')
    op.drop_index(op.f('ix_users_handle'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_file_storage_storage_id'), table_name='file_storage')
    op.drop_index(op.f('ix_file_storage_sha256'), table_name='file_storage')
    op.drop_table('file_storage')
    # ### end Alembic commands ###
