"""add stars table

Revision ID: 80583bb24ac2
Revises: d237f3fff465
Create Date: 2026-03-19 23:04:56.743584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from app.models.types import JSONType  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = '80583bb24ac2'
down_revision: Union[str, None] = 'd237f3fff465'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
